---
- assert:
    that:
      - wildfly_user is defined
      - jdbc_driver_module_dir is defined
      - jdbc_driver_module_name is defined
      - jdbc_driver_jar_installation_path is defined
      - jdbc_driver_jar_filename is defined
      - jdbc_driver_module_name is defined
    quiet: true
    fail_msg: 'Required variables not provided.'

- set_fact:
    wildfly_group: "{{ wildfly_user }}"
  when:
    - not wildfly_group is defined

- name: "Set up module dir for JDBC Driver: jdbc_driver_module_dir"
  file:
    path: "{{ jdbc_driver_module_dir }}"
    state: directory
    recurse: yes
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"

- name: "Retrieve Wildfly JDBC Driver from {{ jdbc_driver_jar_url }}"
  uri:
    url: "{{ jdbc_driver_jar_url }}"
    dest: "{{ jdbc_driver_jar_installation_path }}"
    group: "{{ wildfly_user }}"
    owner: "{{ wildfly_group }}"
    creates: "{{ jdbc_driver_jar_installation_path }}"
  when:
    - jdbc_driver_jar_url is defined

- set_fact:
    module_xml_template: "{{ override_module_xml_template | default('templates/jdbc_driver_module.xml.j2') }}"

- name: "Deploy module.xml for Postgres JDBC Driver"
  template:
    src: "{{ module_xml_template }}"
    dest: "{{ jdbc_driver_module_dir }}/module.xml"
    group: "{{ wildfly_user }}"
    owner: "{{ wildfly_group }}"
