---
- name: Check that required information has been provided
  assert:
    that:
      - supported_arch_by_os is defined
      - ansible_distribution is defined
      - ansible_distribution_major_version is defined
    quiet: true

- name: "Identify OS"
  set_fact:
     cc_os_id: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}"

- block:
    - set_fact:
        fail_msg:
          - "Operating System is not compliant with Common Criteria: {{ cc_os_id }}"

    - name: "Check if OS {{ cc_os_id }} is in compliance with Common Criteria"
      assert:
        that:
          - supported_arch_by_os.{{ cc_os_id }} is defined
        fail_msg: "{{ fail_msg[0] }}"
        quiet: true
  rescue:
    - set_fact:
        compliance_violations: "{{ (compliance_violations | int) + 1 }}"
        compliance_issues: "{{ compliance_issues + fail_msg }}"

- block:
    - set_fact:
        fail_msg:
          - "Architecture is not in compliance with Common Criteria recommendation: {{ ansible_architecture }}"

    - name: "Check if arch is supported for OS {{ cc_os_id }}"
      assert:
        that:
          - ansible_architecture in supported_arch_by_os.{{ cc_os_id }}
        fail_msg: "{{ fail_msg[0] }}"
        quiet: true
  rescue:
    - set_fact:
        compliance_violations: "{{ (compliance_violations | int) + 1 }}"
        compliance_issues: "{{ compliance_issues + fail_msg }}"

- block:
    - set_fact:
        fail_msg:
          - "This version of Java is not in compliance with Common Criteria recommendations: {{ java_version }}"

    - name: "Check that the Java version used is in compliance with Common Criteria recommendations: {{ java_home }} /  {{ compliant_jdk_by_os.RedHat7.openjdk[0] }}"
      assert:
        that:
          - compliant_jdk_by_os.{{ cc_os_id }} is defined
          - compliant_jdk_by_os.{{ cc_os_id }}.{{ jdk_id }} is defined
    #      - java_version in compliant_jdk_by_os.{{ cc_os_id }}.{{ jdk_id }}
        fail_msg: "{{ fail_msg[0] }}"
        quiet: true
  rescue:
    - set_fact:
        compliance_violations: "{{ (compliance_violations | int) + 1 }}"
        compliance_issues: "{{ compliance_issues + fail_msg }}"


